"""First Migration

Revision ID: 5d6aef7e092f
Revises: 
Create Date: 2023-04-03 22:04:21.449917

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d6aef7e092f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tutors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('confirm_hashed_password', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tutors_email'), 'tutors', ['email'], unique=True)
    op.create_index(op.f('ix_tutors_id'), 'tutors', ['id'], unique=False)
    op.create_index(op.f('ix_tutors_name'), 'tutors', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tutors_name'), table_name='tutors')
    op.drop_index(op.f('ix_tutors_id'), table_name='tutors')
    op.drop_index(op.f('ix_tutors_email'), table_name='tutors')
    op.drop_table('tutors')
    # ### end Alembic commands ###
