"""Add shelter

Revision ID: d8ea7db98e8a
Revises: 5d6aef7e092f
Create Date: 2023-04-03 22:21:23.300277

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8ea7db98e8a'
down_revision = '5d6aef7e092f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shelter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('name_animal', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shelter_city'), 'shelter', ['city'], unique=False)
    op.create_index(op.f('ix_shelter_id'), 'shelter', ['id'], unique=False)
    op.create_index(op.f('ix_shelter_name'), 'shelter', ['name'], unique=False)
    op.create_index(op.f('ix_shelter_name_animal'), 'shelter', ['name_animal'], unique=False)
    op.create_index(op.f('ix_shelter_phone'), 'shelter', ['phone'], unique=False)
    op.create_index(op.f('ix_shelter_state'), 'shelter', ['state'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shelter_state'), table_name='shelter')
    op.drop_index(op.f('ix_shelter_phone'), table_name='shelter')
    op.drop_index(op.f('ix_shelter_name_animal'), table_name='shelter')
    op.drop_index(op.f('ix_shelter_name'), table_name='shelter')
    op.drop_index(op.f('ix_shelter_id'), table_name='shelter')
    op.drop_index(op.f('ix_shelter_city'), table_name='shelter')
    op.drop_table('shelter')
    # ### end Alembic commands ###
